/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaProject;

import java.io.*;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author line8847
 */
public class eventsFrame extends javax.swing.JFrame {
    private EventsList eList;
    DefaultListModel model;
    private String filePath;
    /**
     * Creates new form eventsFrame
     */
    public eventsFrame(String user) throws IOException {
        initComponents();
        userLabel.setText(user);
        model = new DefaultListModel();
        eList = new EventsList();
        filePath = "src/JavaProject/accounts/"+user+".txt";
        Scanner file = new Scanner(new File(filePath));
        file.nextLine();
        while (file.hasNextLine()){
            String temp = file.nextLine();
            int year = Integer.parseInt(temp.substring(0, temp.indexOf(" ")));
            int nextIndex = temp.indexOf(" ", temp.indexOf(" ")+1);
            int dateIndex = temp.indexOf(" ", nextIndex+1);  
            String month = temp.substring(temp.indexOf(" ")+1, nextIndex);
            int date = Integer.parseInt(temp.substring(nextIndex+1, dateIndex));
            String data = temp.substring(dateIndex+1);
            eList.addEvent(new Events(year, month, date, data));
        }
        eList.organize();
        System.out.println(eList.getList());
        for (Events e: eList.getList()){
            model.addElement(e.toString());
            
        }
        allEvents.setModel(model); 
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        monTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        infoTxt = new javax.swing.JTextField();
        createB = new javax.swing.JButton();
        refreshB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        allEvents = new javax.swing.JList();
        userLabel = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Create new event:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        yearTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        jLabel1.setText("Year");

        jLabel3.setText("Month");

        jLabel4.setText("Date");

        jLabel5.setText("Description:");

        infoTxt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        createB.setText("Create");
        createB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBActionPerformed(evt);
            }
        });

        refreshB.setText("Refresh");
        refreshB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(allEvents);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userLabel.setText("You");

        error.setForeground(new java.awt.Color(10, 0, 0));

        deleteButton.setText("Delete All Events");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1)))
                        .addGap(111, 111, 111)
                        .addComponent(refreshB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(createB)
                        .addGap(51, 51, 51)
                        .addComponent(error)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(dateTxt)
                            .addComponent(monTxt)
                            .addComponent(yearTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(refreshB)
                        .addGap(259, 259, 259)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createB)
                            .addComponent(error)
                            .addComponent(deleteButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void refreshBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBActionPerformed
        // TODO add your handling code here:
        eList.organize();
        model.clear();
        for (Events e: eList.getList()){
            model.addElement(e.toString());
        }
        
        allEvents = new JList(model);
        
    }//GEN-LAST:event_refreshBActionPerformed

    private void createBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBActionPerformed
        // TODO add your handling code here:
        if (yearTxt.getText().isEmpty() && monTxt.getText().isEmpty() || dateTxt.getText().isEmpty()||infoTxt.getText().isEmpty()){
            error.setText("Error. Incorrect input.");
            yearTxt.setText("");
            monTxt.setText("");
            dateTxt.setText("");
            infoTxt.setText("");
        }
        else{
            
            try{
                Events temp = new Events(Integer.parseInt(yearTxt.getText()), Integer.parseInt(monTxt.getText()), Integer.parseInt(dateTxt.getText()), infoTxt.getText());
                eList.addEvent(temp);
                eList.record(temp, filePath);
                model.addElement(temp.toString());
                allEvents = new JList(model);
                yearTxt.setText("");
                monTxt.setText("");
                dateTxt.setText("");
                infoTxt.setText("");
                error.setText("");
            }
            catch (IOException e){

            }
            catch (NumberFormatException e){
                error.setText("Error. Incorrect input.");
            }
            
        }
        
    }//GEN-LAST:event_createBActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        eList = new EventsList();
        File file = new File(filePath); 
        file.delete();
        File f2 = new File(filePath);
        try{
            f2.createNewFile();
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true)); 
            writer.newLine();
            writer.close();
            model.clear();
            allEvents = new JList(model);
        }
        catch (IOException e){
            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList allEvents;
    private javax.swing.JButton createB;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel error;
    private javax.swing.JTextField infoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monTxt;
    private javax.swing.JButton refreshB;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
